version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
sphinx:
  configuration: documentation/conf.py
formats: all
python:
  install:
    - requirements: documentation/requirements.txt
    - path: .
