//
// Created by li002252 on 9/2/22.
//

#ifndef BUILDALL_STANDALONE_SV2NL_INCLUDE_OPTIONS_HPP_
#define BUILDALL_STANDALONE_SV2NL_INCLUDE_OPTIONS_HPP_

#define SV2NL_USE_CACHE ON

#endif  // BUILDALL_STANDALONE_SV2NL_INCLUDE_OPTIONS_HPP_
