# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import sys
import sphinx
from sphinx.util import logging
from datetime import datetime

import subprocess
import os
import shutil

logger = logging.getLogger("sphinx")
logger.log("info", f"sphinx version: {sphinx.__version__}")
logger.log("info", f"python version: {sys.executable}")


# -- doxygen setup in rtd------------------------------------------------------------


def configure_doxyfile(input_dir, output_dir):
    with open('Doxyfile.in', 'r') as file:
        file_data = file.read()

    file_data = file_data.replace('@DOXYGEN_PROJECT_ROOT@', input_dir)
    file_data = file_data.replace('@DOXYGEN_OUTPUT_DIRECTORY@', output_dir)

    with open('Doxyfile', 'w') as file:
        file.write(file_data)


def run_doxygen():
    # Check if we're running on Read the Docs' servers
    if os.environ.get('READTHEDOCS', None) is not None:
        breathe_projects = {}
        input_dir = '../library'
        output_dir = 'build'
        configure_doxyfile(input_dir, output_dir)
        subprocess.call('doxygen', shell=True)
        breathe_projects['binary'] = output_dir + '/xml'


# Breathe Configuration
breathe_default_project = "binary"

run_doxygen()

# -- doxygen setup in rtd------------------------------------------------------------

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'binary'
author = "Yangyang Li"
copyright = f"{datetime.now().year}, {author}"
release = '1.0.1'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

todo_include_todos = True
sphinx_tabs_valid_builders = ['linkcheck']
source_suffix = ['.md']

# Do not warn about external images (status badges in README.rst)
suppress_warnings = ['image.nonlocal_uri']

extensions = ["breathe",
              # "sphinx.ext.autodoc",
              # https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html#module-sphinx.ext.graphviz
              "sphinx.ext.graphviz",
              # https://github.com/useblocks/sphinx-needs
              "sphinx_needs",
              # https://www.sphinx-doc.org/en/master/usage/extensions/todo.html#confval-todo_include_todos
              "sphinx.ext.todo",
              'sphinx_copybutton',
              "sphinxcontrib.mermaid",
              'sphinx_tabs.tabs',
              "myst_parser"]

myst_heading_anchors = 3
myst_enable_extensions = [
    "dollarmath",
    "amsmath",
    "deflist",
    "fieldlist",
    "html_admonition",
    "html_image",
    "colon_fence",
    "smartquotes",
    "replacements",
    "linkify",
    "strikethrough",
    "substitution",
    "tasklist",
]

templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = ['_static']

# --Customization of theme---------------------------------------------
# https://alabaster.readthedocs.io/en/latest/customization.html

html_theme_options = {
    # 'logo': 'logo.png',
    'github_user': 'ylab-hi',
    'github_repo': 'BINARY',
    'github_banner': True,
    'github_button': True,
    'github_type': 'star',
    'github_count': 'true',
    'description': 'Modern C++ Bioinformatics Algorithm Library',
    'codecov_button': True,
    'anchor': '#DDA0DD',

}
