name: Documentation

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    name: Build and publish documentation
    runs-on: macos-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: |
          #          pip install --constraint=.github/workflows/constraints.txt pip
               pip --version

      - name: Upgrade pip in virtual environments
        shell: python
        run: |
          import os
          import pip
          with open(os.environ["GITHUB_ENV"], mode="a") as io:
              print(f"VIRTUALENV_PIP={pip.__version__}", file=io)


      - name: Install dependencies
        run: |
          python -V
          brew install doxygen
          pip install -r documentation/requirements.txt

      - name: Build
        run: |
          cmake -Sdocumentation -Bbuild
          cmake --build build --target BinaryDocs

#      - name: Publish
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./build/doxygen/html
