name: MacOS

on:
  push:
    branches:
      - master
      - main
      - release*
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  CMAKE_VERSION: 3.14.0

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Configure Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install CMake
        run: bash ./.github/workflows/scripts/install_cmake.sh

      - name: Install autoconf tools
        run: brew install autoconf automake libtool

      - name: configure
        env:
        run: cmake -Stest -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: build
        run: cmake --build build -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug
