name: Standalone

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  CMAKE_VERSION: 3.14.0

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "standalone gcc12"
            os: ubuntu-latest
            cxx: "g++-12"
            cc: "gcc-12"
            build: standalone
            build_type: Debug


    steps:
      - uses: actions/checkout@v2

      - name: Configure APT
        continue-on-error: true
        run: bash ./.github/workflows/scripts/configure_apt.sh

      - name: Install compiler ${{ matrix.cxx }}
        run: sudo apt-get install --yes ${{ matrix.cxx }}

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}


      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: configure
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: cmake -Sstandalone -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: build
        run: cmake --build build -j4

      - name: run sv2nl
        run: ./build/sv2nl
