name: Standalone

on:
  push:
    branches:
      - release*
  pull_request:
    branches:
      - release*

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  CMAKE_VERSION: 3.14.0

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{matrix.name}}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    strategy:
      matrix:
        include:
          - name: "standalone gcc11"
            cxx: "g++-11"
            cc: "gcc-11"
            build: standalone
            build_type: Release
    #          - name: "standalone gcc10"
    #            cxx: "g++-10"
    #            cc: "gcc-10"
    #            build: standalone
    #            build_type: Release


    steps:
      - uses: actions/checkout@v2

      - name: Configure APT
        continue-on-error: true
        run: bash ./.github/workflows/scripts/configure_apt.sh

      - name: Install CMake
        run: bash ./.github/workflows/scripts/install_cmake.sh

      - name: Install compiler ${{ matrix.cxx }}
        run: sudo apt-get install --yes ${{ matrix.cxx }} autoconf

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}


      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version
          env ${{ matrix.cc }} --version

      - name: configure
        run: cmake -Sstandalone -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER=${{matrix.cc}} -DCMAKE_CXX_COMPILER=${{matrix.cxx}}

      - name: build
        run: cmake --build build -j4

      - name: run sv2nl
        run: ./build/sv2nl -h
